export default [
  {
    name: "EAT & DRINK",
    restaurants: [
      "53",
      "Aquavit",
      "Baccarat Hotel",
      "Estiatorio Milos",
      "Harry Cipriani",
      "Il Gattopardo",
      "Jean-Georges",
      "La Grenouille",
      "Le Bernardin",
      "Le Bilboquet",
      "Le Rock",
      "L’ami Pierre",
      "Lodi",
      "Marea",
      "Mastro's Steakhouse",
      "Michael’s",
      "Monkey Bar",
      "NARO",
      "Nobu 57",
      "Pebble Bar",
      "Per Se",
      "Polo Bar",
      "Quality Bistro",
      "Rainbow Room",
      "St. Regis",
      "Taru",
      "The Grill",
      "The Plaza",
    ],
  },
  {
    name: "CULTURE",
    restaurants: [
      "Baretto Jazz Bar",
      "Birdland",
      "Broadway",
      "Carnegie Hall",
      "Carpenters Workshop Gallery",
      "Christie’s Auction House",
      "David Benrimon Fine Art",
      "Marian Goodman Gallery",
      "Museum of Arts and Design",
      "Museum of Modern Art (MoMA)",
      "New York City Center",
      "Phillips",
      "Radio City Music Hall",
      "Rockefeller Center",
      "The Paley Center for Media",
      "The Paris Theater",
    ],
  },
  {
    name: "SHOPPING",
    restaurants: [
      "Audemars Piguet",
      "Bauman Rare Books",
      "Bergdorf Goodman",
      "Bulgari",
      "Burberry",
      "Cartier",
      "Chanel",
      "Dior",
      "Giorgio Armani",
      "Gucci",
      "Harry Winston",
      "Louis Vuitton",
      "Loro Piana",
      "McNally Jackson Booksellers",
      "Piaget",
      "Prada",
      "Rolex",
      "Saks Fifth Avenue",
      "Van Cleef & Arpels",
      "Wempe",
      "Zegna",
    ],
  },
  {
    name: "RECREATION",
    restaurants: [
      "Aida Bicaj",
      "Central Park",
      "Central Rock Gym",
      "Equinox",
      "Guerlain Spa",
      "Hudson River Park",
      "John Barrett Salon",
      "La Prairie Spa",
      "New York Cycle Club",
      "Physique 57",
      "Pure Barre",
      "Sage + Sound",
      "Sheep Meadow",
      "Spa de La Mer",
      "The Yoga Trail",
      "Wollman Rink",
    ],
  },
];
