
export default  [
  {
    title: "LIVING ROOMS",
    button: "SEE ALL INTERIOR FEATURES",
    text: "Living spaces exude a warm and inviting ambiance. Expansive and breathtaking views are framed by triple-glazed full-height windows, and a wealth of considered finishes—wide-plank oak flooring, grand walnut entry doors, and custom bronze hardware designed by Thierry Despont—combine to create a truly artful atmosphere.",
    images: [6, 5],
    features: [
      "Oversized walnut entry doors with custom Thierry Despont–designed burnished bronze hardware by E.R. Butler & Co",
      "Wide plank solid American oak floors and custom wood baseboards",
      "Tray and cove ceilings up to 11 feet high",
      "Triple-glazed, floor-to-ceiling low-iron glass windows that open to fresh air",
      "All windows fitted with motorized Lutron solar shades; additional blackout shades in bedrooms",
      "Humidified and filtered fresh air supply system",
      "Linear diffusers for heating and cooling with individual thermostatic controls for primary rooms",
      "Four high-speed passenger elevators to residences, some with direct access into homes",
      "Emergency generator outlets",
    ],
  },
  {
    title: "KITCHENS",
    button: "SEE ALL KITCHEN FEATURES",
    text: "Chef-standard kitchens are replete with glass-fronted Molteni&C cabinets designed by Thierry Despont, luminous marble surfaces, premium appliances from Miele and Sub-Zero, and polished nickel Dornbracht fixtures.",
    images: [7, 8],
    features: [
      "Polished Statuary marble countertops and islands with beveled edge detailing",
      "Custom back-painted glass cabinetry with polished nickel detailing designed by Thierry Despont for Molteni&C",
      "Back-lit Statuary marble backsplash with polished finish",
      "Dornbracht polished nickel fittings",
      "Fully-integrated Sub-Zero refrigerators/freezers and Miele appliances",
      "Wine refrigerators",
      "Coffee maker/machine",
    ],
  },
  {
    title: "BATHROOMS",
    button: "SEE ALL BATHROOM FEATURES",
    text: "Spa-like bathrooms blend tradition and originality, featuring Italian-finished Verona limestone surfaces and premium fixtures. Select residences feature heated limestone floors and distinctive lollipop vanity mirrors, designed by Thierry Despont, which can be raised and lowered according to one’s preference.",
    images: [9, 10],
    features: [
      "Verona limestone flooring in high-honed finish and Noir St. Laurent marble feature walls",
      "Polished Persian Golden Travertine feature walls",
      "Carved Verona limestone vanity sinks with custom Thierry Despont–designed polished nickel automated mirrors",
      "Radiant floor heating",
      "Dornbracht polished nickel fittings and accessories",
    ],
  },
  {
    title: "BEDROOMS",
    button: "SEE ALL BEDROOM FEATURES",
    text: "The residences’ bedrooms share the rich layering of finishes and detailing found throughout the rest of the living spaces, as well as Nouvel and Despont’s overall approach to light and space. They are tranquil retreats where an atmosphere of luxury and comfort extends throughout.",
    images: [11, 12],
    features: [
      "Wide plank solid American oak floors",
      "Custom wood baseboards",
      "Tray and cove ceilings up to 11 feet high",
      "Triple-glazed, floor-to-ceiling low-iron glass windows that open to fresh air",
      "Motorized Lutron solar shades",
      "Additional blackout shades in bedrooms",
      "Humidified and filtered fresh air supply system",
      "Linear diffusers for heating and cooling with individual thermostatic controls",
    ],
  },
];
